### ISSUE TITLE
Chefbot -> MD25 controller and arduino mega modification.

### ISSUE THREAD

**Issue by Tondy** [qboticslabs/Chefbot_ROS_pkg#1]
Hello 

I have the Chefbot successfully setup. Instead of using the tiva launch pad board. I am using the arduin mega and a pololu MD25 motor controller with integrated encoders. http://www.robot-electronics.co.uk/htm/md25i2c.htm. The arduino-mega talks  to the MD25 by sending the the range of -128 (full reverse)   0 (Stop)   127 (full forward).  What edits should be made on the pid_velocity.py or other scripts to accommodate this?  For example what to do when dealing with theshold value or min-out and min-out.

Hope you can help.

Cheers.

**Comment by qboticslabs** [comment]
Hi

In the present code, the value sending from P.C to Tiva C Launchpad is 0 -> 1023 and 0 -> -1023. 

You can change the limits in **chefbot_bringup/launch/robot_standalone.launch**

In this file , you can see the out_min & out_max, which is the range of output value !!

```

  <node name="lpid_velocity" pkg="chefbot_bringup" type="pid_velocity.py" output="screen">
 
      <rosparam param="out_min">-1023</rosparam>
      <rosparam param="out_max">1023</rosparam>

  </node>

```
