### ISSUE TITLE
How to call callback function?

### ISSUE THREAD

**Issue by KFBIT** [qboticslabs/Chefbot_ROS_pkg#2]
Hello:
         your diff_tf.cpp has ros::spinOnce() so I know how to call Odometry_calc::leftencoderCb() and Odometry_calc::rightcoderCb().

          But I found your diff_tf.py and pid_velocity.py don't rospy.spinOnce().I wonder how to call callback function?

          Looking forward to your reply.Thank you.

**Comment by qboticslabs** [comment]
Hi KFBIT

Thanks for pointing this, Can you please check this node working without spinOnce()?  I got it working and please get back to me if it is not working in your side. I will correct the code then 

Regards
Lentin Joseph
