### ISSUE TITLE
Chapter 9 : Aiml > start_speech_chat.launch

### ISSUE THREAD

**Issue by Tondy** [qboticslabs/Chefbot_ROS_pkg#4]
After creating Pyaiml  package as instructed with:

catkin_create_pkg ros_aiml rospy std_msgs sound_play

I copied the files from chapter 9 into ros_aiml package file.

I ran catkin_make and sourced the /devel/setup.bash

I then changed launch files to:

<param name="aiml_path" value="/home/tondy/catkin_ws/src/ros_aiml/data" />

For some reason the error below constantly appears. Scripts folder does contain 
the python scripts. Not sure whats happening.

ERROR: cannot launch node of type [ros_aiml/aiml_server.py]: can't locate node [aiml_server.py] in package [ros_aiml]
process[soundplay_node-2]: started with pid [7720]
ERROR: cannot launch node of type [ros_aiml/aiml_tts_client.py]: can't locate node [aiml_tts_client.py] in package [ros_aiml]
ERROR: cannot launch node of type [ros_aiml/aiml_speech_recog_client.py]: can't locate node [aiml_speech_recog_client.py] in package [ros_aiml]

**Comment by qboticslabs** [comment]
Hi

Can you first do the following command

$roscd ros_aiml

If it is making error, you have to check the path of package

If it is ok, then goto the node folder and change permission of nodes using following command

$sudo chmod +X node_name

And try to run again !!

**Comment by Tondy** [comment]
Hello 

Thank very much it now works. But nothing happens when I speak nothing happens. The aiml data file is correctly set. Maybe the recognition needs training ? Not sure why these no response this is the output.

core service [/rosout] found
process[aiml_server-1]: started with pid [5134]
process[soundplay_node-2]: started with pid [5135]
process[aiml_tts-3]: started with pid [5138]
process[aiml_speech_recog-4]: started with pid [5139]
/home/tondy/catkin_ws/src/ros_aiml/data
[INFO] [WallTime: 1463143411.987085] Starting Speech Recognition
Starting TTS
[INFO] [WallTime: 1463143413.105861] Starting listening to response
Loading brain from standard.brn... done (98290 categories in 4.13 seconds)
Kernel bootstrap completed in 4.13 seconds
[INFO] [WallTime: 1463143416.001864] Starting ROS AIML Server

Many thanks for the help.

**Comment by qboticslabs** [comment]
Check the mic configuration and adjust mic volume until it triggers a detected word. You have to train the models for accuracy !!

**Comment by Tondy** [comment]
Hello 

So I have checked the microphone and have tested it. Its partially working. But very in accurate. Its not clear how I can improve the training . What could be the best step by step. I have read you create a text file of words/sentence to recognize upload it to pocket sphinx website and you get a lexicon or language file. But where do you put the new file in file system. Can you direct me into right direction to improve accuracy?

Many thanks.

The book is best robot book ever.

Cheers

**Comment by Tondy** [comment]
Currently found these instructions.::::::::

Creating a Language Model
Create a text file, containing a list of words/sentences we want to be recognized
For instance ..
Okay Pi
Open Garage
Start Translator
Shutdown
What is the weather in Ramona
What is the time
Upload the text file here: http://www.speech.cs.cmu.edu/tools/lmtool-new.html
and then download the generated Pronunciation Dictionary and Language Model
For the the text file mentioned above, this is what the tool generates::

Not sure where to place the generated file.

**Comment by qboticslabs** [comment]
Hi Tondy

Sorry for the delay !!! Was in ICRA from 15th to 26th. I can give you the instruction link to train the LM of Sphinx and Julius !!!

http://cmusphinx.sourceforge.net/wiki/tutorialam

Julius Training 

http://julius.osdn.jp/en_index.php?q=index-en.html#grammar

It is a tedious  work, but still you can make a try !!!

**Comment by Tondy** [comment]
Hello

So I finally used this tool to train a lm and dic file. http://www.speech.cs.cmu.edu/tools/lmtool-new.html

The recognizer recognizes the words.  Would like to know if they is any way to stop constant random 
aiml input to be feed with out some one saying something. 

So when I switch on the ros_aiml I say a word and it successfully recognizes it. and gives proper response. After that the system starts feeding in random sentences that I am not saying and generating responses. This goes on for a while and some times suddenly stops or keeps going.

Hope you can help.

**Comment by qboticslabs** [comment]
Hi Tondy

The speech recognizer can generate a text whenever there is any sound. The sound can be noise too. 

Whenever there is a speech to text data, it will send to aiml node, and it will say response, which may not have any meaning.

What you can do is, you can just modify aiml node or speech node, in a such a way that, respond only if a  meaningful word or sentence received, other vice ignore.

**Comment by Tondy** [comment]
Ok.

How can I do this. I was looking into  limiting the number of aiml files but looks like it would not help.

Many thanks.

**Comment by PhoenixDai0820** [comment]
> Ok.
> 
> How can I do this. I was looking into limiting the number of aiml files but looks like it would not help.
> 
> Many thanks.



> Hello
> 
> So I finally used this tool to train a lm and dic file. http://www.speech.cs.cmu.edu/tools/lmtool-new.html
> 
> The recognizer recognizes the words. Would like to know if they is any way to stop constant random
> aiml input to be feed with out some one saying something.
> 
> So when I switch on the ros_aiml I say a word and it successfully recognizes it. and gives proper response. After that the system starts feeding in random sentences that I am not saying and generating responses. This goes on for a while and some times suddenly stops or keeps going.
> 
> Hope you can help.

Hi, TonderaiZR,

I got the same problem as you did 4 years ago. Could you please let me know where to place .lm and .dic files?

**Comment by TonderaiZR** [comment]
Hi Phoenix 

Having a good corpus helps. Also, make sure the mic is a distance from the speaker so you do not get feedback from the speaker coming back into the mic. You can also customize your python code to ignore non recognized words. For example, a keyword when recognized will trigger further recognization otherwise will be ignored.

Another solution can be having a volume threshold on the microphone.

Hope this helps.

**Comment by PhoenixDai0820** [comment]
Hi, TonderaiZR, 

Thanks a lot for your kind reply!

My problem is, aftering launching "ros_aiml start_speech_chat.launch", there is no response for my voice. It seems that the speech recognizer is not  envoked, eventhough no error message in the ROS terminal. I adjust may laptop mic volume, but it does not work. Have you ever met this problem before?

Just as what you did, I generated the .dic and .lm files from http://www.speech.cs.cmu.edu/tools/lmtool-new.html. However, I have no idea where to place these files. Could you please let me know which folder should these files be placed?

I want to use this speech recognizer in my hobby project. I went through this Siri-like Chatbot project, and have successully run other launch files. But I can not make this final launch file run. I will appreciate a lot if you can give me some guidance and advices.

Thanks again for your time in answering my questions!

Best regards,
Phoenix

**Comment by TonderaiZR** [comment]
Hi

I will have to check the folder and message you. But make sure the permissions on the files are set sudo chmod +X node_name.  
Also, test your Linux audio settings and audio drivers if you using an usb mic & speaker dongle.

**Comment by PhoenixDai0820** [comment]
Hi, TonderaiZR,

Thank you so much for such a quick reply!

Yes, I used "sudo chmod +X node_name" for every file to be run. 
I don't use usb mic & speaker dongle. I tested the internal mic of my laptop, and it seems work well.

Thanks again for your help in checking the folder. I am looking forward to your message sincerely!
