### ISSUE TITLE
Arduino Port

### ISSUE THREAD

**Issue by PeterChauYEG** [qboticslabs/Chefbot_ROS_pkg#7]
Hi there,

The Tiva C used for this project didn't work out for me. My boards were defective and I got fed up with them so I used an Arduino instead. I ported your Tiva C code to [Arduino C](https://github.com/PeterChauYEG/chefbot-arduino).

Would you like me to create a Pull Request for this repository with my ported code?

Thanks for the book,

Peter Chau

**Comment by qboticslabs** [comment]
Hello Peter

Great work. Please do the pull request. Please create a new branch called arduino and do the pull request.

Thanks

**Comment by PeterChauYEG** [comment]
Hi,

It looks like I made the Pull Request incorrectly. I will try that again.
